# Generated by Django 5.0.6 on 2025-04-10 13:37

from django.db import migrations, models

def remove_social_permissions_and_data(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    try:
        # Get content types for the app
        content_types = ContentType.objects.filter(app_label='social')

        # Remove all permissions for those content types
        Permission.objects.filter(content_type__in=content_types).delete()

        # Delete all rows from the SocialMediaIntegration table
        SocialMediaIntegration = apps.get_model('social', 'SocialMediaIntegration')
        SocialMediaIntegration.objects.all().delete()

    except Exception as e:
        print(f"Error during cleanup: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('social_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaintegration',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(remove_social_permissions_and_data),
    ]
