# Generated by Django 5.0.6 on 2025-04-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_config', '0002_socialmediaintegration_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaintegration',
            name='page_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmediaintegration',
            name='page_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='socialmediaintegration',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
