# Generated by Django 5.0.6 on 2025-04-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_config', '0003_socialmediaintegration_page_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediaintegration',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='socialmediaintegration',
            name='user_id',
        ),
        migrations.AddField(
            model_name='socialmediaintegration',
            name='social_user_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
