# Generated by Django 5.0.6 on 2025-04-17 12:56

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_default_user(apps, schema_editor):
    # Get the CustomUser model
    CustomUser = apps.get_model('users', 'CustomUser')

    # Create a default superuser
    CustomUser.objects.create(
        username='admin',
        email='admin@gmail.com',
        password=make_password('Admin@123'),  # Hash the password
        is_superuser=True,
        is_staff=True,
        is_active=True,
    )

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_user),
    ]
