# Generated by Django 5.0.6 on 2025-04-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaintegration',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
